In [1]:
import numpy as np

In [2]:
raw_data=[[2.5,2.4],[0.5,0.7],[2.2,2.9],[1.9,2.2],[3.1,3.0],
          [2.3,2.7],[2.0,1.6],[1.0,1.1],[1.5,1.6],[1.1,0.9]]

In [3]:
#将数据转换成矩阵
matrix = np.mat(raw_data)
matrix

matrix([[2.5, 2.4],
        [0.5, 0.7],
        [2.2, 2.9],
        [1.9, 2.2],
        [3.1, 3. ],
        [2.3, 2.7],
        [2. , 1.6],
        [1. , 1.1],
        [1.5, 1.6],
        [1.1, 0.9]])

In [4]:
#求平均值  axis=0 ==>对各项求平均值
mean_matrix = np.mean(matrix,axis=0)
mean_matrix

matrix([[1.81, 1.91]])

In [5]:
#去中心化后的数据  全体数据减去平均值
normal_data  =matrix - mean_matrix
normal_data

matrix([[ 0.69,  0.49],
        [-1.31, -1.21],
        [ 0.39,  0.99],
        [ 0.09,  0.29],
        [ 1.29,  1.09],
        [ 0.49,  0.79],
        [ 0.19, -0.31],
        [-0.81, -0.81],
        [-0.31, -0.31],
        [-0.71, -1.01]])

In [6]:
#计算特征值和特征向量
covMatrix = np.cov(normal_data,rowvar=0)
covMatrix

array([[0.61655556, 0.61544444],
       [0.61544444, 0.71655556]])

In [8]:
#计算方阵的特征值和特征向量
eigValues,eigVectors = np.linalg.eig(covMatrix)
print("eigValus:",eigValues)
print("eigVectors:",eigVectors)

eigValus: [0.0490834  1.28402771]
eigVectors: [[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]


In [9]:
#对特征值进行排序
eigValuesIndex = np.argsort(eigValues)
eigValuesIndex

array([0, 1], dtype=int64)

In [10]:
#保留前k个最大的特征值
eigValuesIndex = eigValuesIndex[:-(1000000):-1]
eigValuesIndex

array([1, 0], dtype=int64)

In [13]:
#计算出对应的特征向量
trueEigVectors = eigVectors[:,eigValuesIndex]
trueEigVectors

array([[-0.6778734 , -0.73517866],
       [-0.73517866,  0.6778734 ]])

In [14]:
#选择较大特征值对应的特征向量
maxvector_eigval = trueEigVectors[:,0]
maxvector_eigval

array([-0.6778734 , -0.73517866])

In [15]:
#执行PCA变换：Y=PX得到的Y就是PCA降维后的值  数据集矩阵
#maxvector_eigval为1行2列，normal_data.T为2行10列
pca_result =maxvector_eigval * normal_data.T

In [16]:
maxvector_eigval.shape

(2,)

In [17]:
normal_data.T.shape

(2, 10)

In [18]:
pca_result

matrix([[-0.82797019,  1.77758033, -0.99219749, -0.27421042, -1.67580142,
         -0.9129491 ,  0.09910944,  1.14457216,  0.43804614,  1.22382056]])

In [19]:
pca_result.shape

(1, 10)